# Generated by Django 6.0.5 on 2026-05-26 22:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ear_tag', models.CharField(max_length=50)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SowEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INSEMINATION', 'Inseminacja'), ('FARROWING', 'Oproszenie'), ('WEANING', 'Odsadzenie')], max_length=20)),
                ('event_date', models.DateField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sows.sowmodel')),
            ],
        ),
    ]
