# Generated by Django 6.0.5 on 2026-05-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SowModel',
            fields=[
                ('sow_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ear_tag', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SowEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INSEMINATION', 'Inseminacja'), ('FARROWING', 'Oproszenie'), ('WEANING', 'Odsadzenie')], max_length=20)),
                ('event_date', models.DateField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('sows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sows.sowmodel')),
            ],
        ),
    ]
