# Generated by Django 6.0.5 on 2026-05-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soweventmodel',
            old_name='sows',
            new_name='sow',
        ),
        migrations.RemoveField(
            model_name='sowmodel',
            name='breed',
        ),
    ]
