# Generated by Django 6.0.5 on 2026-05-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa szczepienia')),
                ('days_before_farrowing', models.IntegerField(blank=True, help_text='Ile dni przed porodem?', null=True)),
                ('interval_months', models.IntegerField(blank=True, help_text='Cyklicznie co X miesięcy?', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='soweventmodel',
            name='event_type',
            field=models.CharField(choices=[('INSEMINATION', 'Inseminacja'), ('PREGNANCY_CHECK', 'Badanie'), ('FARROWING', 'Oproszenie'), ('WEANING', 'Odsadzenie'), ('VACCINATION', 'Szczepienie')], max_length=20),
        ),
    ]
