# Generated by Django 6.0.5 on 2026-05-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0002_vaccinationplanmodel_alter_soweventmodel_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='days_after_event',
            field=models.IntegerField(blank=True, help_text='Ile dni po zdarzeniu?', null=True),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='event_source',
            field=models.CharField(blank=True, choices=[('FARROWING', 'Oproszenie'), ('INSEMINATION', 'Inseminacja')], help_text='Zdarzenie odniesienia', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='reminder_days_ahead',
            field=models.IntegerField(default=7, help_text='Ile dni wcześniej wyświetlać przypomnienie?'),
        ),
        migrations.AlterField(
            model_name='vaccinationplanmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nazwa szczepienia'),
        ),
    ]
