# Generated by Django 6.0.5 on 2026-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0003_vaccinationplanmodel_days_after_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sowmodel',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sowmodel',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Czy zarchiwizowana?'),
        ),
    ]
