# Generated by Django 6.0.5 on 2026-07-12 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0007_mortality_reports_and_miscarriage'),
    ]

    operations = [
        migrations.AddField(
            model_name='soweventmodel',
            name='cycle_id',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Identyfikator cyklu'),
        ),
        migrations.AddField(
            model_name='soweventmodel',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Planowany termin'),
        ),
        migrations.AddField(
            model_name='soweventmodel',
            name='vaccination_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_events', to='sows.vaccinationplanmodel', verbose_name='Plan szczepienia'),
        ),
        migrations.AddField(
            model_name='soweventmodel',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nazwa szczepienia'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='excluded_sows',
            field=models.ManyToManyField(blank=True, related_name='excluded_vaccination_plans', to='sows.sowmodel', verbose_name='Wykluczone maciory'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='first_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data pierwszego terminu'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='interval_unit',
            field=models.CharField(blank=True, choices=[('DAYS', 'dni'), ('WEEKS', 'tygodnie'), ('MONTHS', 'miesiące'), ('YEARS', 'lata')], max_length=10, null=True, verbose_name='Jednostka interwału'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='interval_value',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Wartość interwału'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Plan aktywny'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='requires_configuration',
            field=models.BooleanField(default=False, verbose_name='Wymaga uzupełnienia konfiguracji'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='schedule_mode',
            field=models.CharField(blank=True, choices=[('FIXED', 'Stały harmonogram'), ('FROM_LAST_COMPLETED', 'Od ostatniego wykonanego szczepienia')], max_length=24, null=True, verbose_name='Tryb harmonogramu'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='scope',
            field=models.CharField(choices=[('ALL', 'Wszystkie aktywne maciory'), ('SELECTED', 'Wybrane aktywne maciory')], default='ALL', max_length=10, verbose_name='Zakres planu'),
        ),
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='selected_sows',
            field=models.ManyToManyField(blank=True, related_name='selected_vaccination_plans', to='sows.sowmodel', verbose_name='Wybrane maciory'),
        ),
        migrations.CreateModel(
            name='VaccinationCycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.CharField(max_length=160, verbose_name='Identyfikator cyklu')),
                ('scheduled_date', models.DateField(verbose_name='Planowany termin')),
                ('status', models.CharField(choices=[('COMPLETED', 'Wykonane'), ('SKIPPED', 'Pominięte')], max_length=12)),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Data wykonania')),
                ('skipped_at', models.DateField(blank=True, null=True, verbose_name='Data pominięcia')),
                ('note', models.TextField(blank=True, verbose_name='Powód lub notatka')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_records', to='sows.vaccinationplanmodel', verbose_name='Plan szczepienia')),
                ('sow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_cycles', to='sows.sowmodel', verbose_name='Maciora')),
            ],
            options={
                'ordering': ('scheduled_date', 'id'),
                'indexes': [models.Index(fields=['plan', 'sow', 'scheduled_date'], name='vacc_cycle_plan_sow_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'sow', 'cycle_id'), name='unique_vaccination_cycle_per_sow')],
            },
        ),
    ]
