# Generated by Django 6.0.5 on 2026-07-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0009_backfill_vaccination_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soweventmodel',
            name='cycle_id',
            field=models.CharField(blank=True, max_length=160, verbose_name='Identyfikator cyklu'),
        ),
        migrations.AlterField(
            model_name='soweventmodel',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nazwa szczepienia'),
        ),
        migrations.AddConstraint(
            model_name='vaccinationcyclemodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('skipped_at__isnull', True), ('status', 'COMPLETED')), models.Q(('completed_at__isnull', True), ('skipped_at__isnull', False), ('status', 'SKIPPED')), _connector='OR'), name='vaccination_cycle_status_dates_valid'),
        ),
    ]
