# Generated by Django 6.0.5 on 2026-07-12 17:48

from django.conf import settings
from django.db import migrations, models


def classify_legacy_mortality(apps, schema_editor):
    MortalityReport = apps.get_model('sows', 'MortalityReportModel')
    MortalityReport.objects.filter(mortality_type='sow').update(mortality_type='MACIORA')
    MortalityReport.objects.filter(mortality_type='post_weaning').update(
        mortality_type='NIEOKRESLONY_PO_ODSADZENIU'
    )


def restore_legacy_mortality_types(apps, schema_editor):
    MortalityReport = apps.get_model('sows', 'MortalityReportModel')
    MortalityReport.objects.filter(mortality_type='MACIORA').update(mortality_type='sow')
    MortalityReport.objects.filter(
        mortality_type__in=(
            'PROSIAK', 'WARCHLAK', 'TUCZNIK', 'NIEOKRESLONY_PO_ODSADZENIU',
        )
    ).update(mortality_type='post_weaning')


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0014_default_automatic_feed_serving'),
        ('sows', '0010_vaccination_cycle_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortalityreportmodel',
            name='mortality_type',
            field=models.CharField(choices=[('MACIORA', 'Maciora'), ('PROSIAK', 'Prosiak'), ('WARCHLAK', 'Warchlak'), ('TUCZNIK', 'Tucznik'), ('NIEOKRESLONY_PO_ODSADZENIU', 'Nieokreślone po odsadzeniu')], max_length=32, verbose_name='Typ upadku'),
        ),
        migrations.RunPython(classify_legacy_mortality, restore_legacy_mortality_types),
        migrations.AddIndex(
            model_name='mortalityreportmodel',
            index=models.Index(fields=['farm', 'mortality_type', '-mortality_date'], name='mortality_farm_type_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='mortalityreportmodel',
            constraint=models.CheckConstraint(condition=models.Q(('mortality_type__in', ('MACIORA', 'PROSIAK', 'WARCHLAK', 'TUCZNIK', 'NIEOKRESLONY_PO_ODSADZENIU'))), name='mortality_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='mortalityreportmodel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='mortality_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='mortalityreportmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mortality_type', 'MACIORA'), ('sow__isnull', False)), models.Q(('mortality_type__in', ('PROSIAK', 'WARCHLAK', 'TUCZNIK', 'NIEOKRESLONY_PO_ODSADZENIU')), ('sow__isnull', True)), _connector='OR'), name='mortality_sow_matches_type'),
        ),
    ]
