# Generated by Django 6.0.5 on 2026-07-16 14:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0014_default_automatic_feed_serving'),
        ('sows', '0011_mortality_types_and_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PigletTransferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Liczba prosiąt')),
                ('transfer_date', models.DateField(verbose_name='Data przeniesienia')),
                ('note', models.TextField(blank=True, verbose_name='Notatka lub przyczyna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Anulowano')),
                ('cancellation_note', models.TextField(blank=True, verbose_name='Powód anulowania')),
            ],
            options={
                'verbose_name': 'Przeniesienie prosiąt',
                'verbose_name_plural': 'Przeniesienia prosiąt',
                'ordering': ('-transfer_date', '-created_at', '-id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='mortalityreportmodel',
            name='mortality_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='mortalityreportmodel',
            name='mortality_sow_matches_type',
        ),
        migrations.AddField(
            model_name='mortalityreportmodel',
            name='farrowing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_weaning_mortality_reports', to='sows.soweventmodel', verbose_name='Cykl odchowu'),
        ),
        migrations.AlterField(
            model_name='mortalityreportmodel',
            name='mortality_type',
            field=models.CharField(choices=[('MACIORA', 'Maciora'), ('PRZED_ODSADZENIEM', 'Prosięta przed odsadzeniem'), ('PROSIAK', 'Prosiak'), ('WARCHLAK', 'Warchlak'), ('TUCZNIK', 'Tucznik'), ('NIEOKRESLONY_PO_ODSADZENIU', 'Nieokreślone po odsadzeniu')], max_length=32, verbose_name='Typ upadku'),
        ),
        migrations.AddConstraint(
            model_name='mortalityreportmodel',
            constraint=models.CheckConstraint(condition=models.Q(('mortality_type__in', ('MACIORA', 'PRZED_ODSADZENIEM', 'PROSIAK', 'WARCHLAK', 'TUCZNIK', 'NIEOKRESLONY_PO_ODSADZENIU'))), name='mortality_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='mortalityreportmodel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('farrowing__isnull', True), ('mortality_type', 'MACIORA'), ('sow__isnull', False)), models.Q(('farrowing__isnull', False), ('mortality_type', 'PRZED_ODSADZENIEM'), ('sow__isnull', False)), models.Q(('farrowing__isnull', True), ('mortality_type__in', ('PROSIAK', 'WARCHLAK', 'TUCZNIK', 'NIEOKRESLONY_PO_ODSADZENIU')), ('sow__isnull', True)), _connector='OR'), name='mortality_sow_matches_type'),
        ),
        migrations.AddField(
            model_name='piglettransfermodel',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_piglet_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Anulował'),
        ),
        migrations.AddField(
            model_name='piglettransfermodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_piglet_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Utworzył'),
        ),
        migrations.AddField(
            model_name='piglettransfermodel',
            name='farm',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='piglet_transfers', to='farms.farmmodel', verbose_name='Gospodarstwo'),
        ),
        migrations.AddField(
            model_name='piglettransfermodel',
            name='source_farrowing',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_piglet_transfers', to='sows.soweventmodel', verbose_name='Oproszenie źródłowe'),
        ),
        migrations.AddField(
            model_name='piglettransfermodel',
            name='target_farrowing',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_piglet_transfers', to='sows.soweventmodel', verbose_name='Oproszenie docelowe'),
        ),
        migrations.AddIndex(
            model_name='piglettransfermodel',
            index=models.Index(fields=['farm', '-transfer_date'], name='piglet_transfer_farm_date_idx'),
        ),
        migrations.AddIndex(
            model_name='piglettransfermodel',
            index=models.Index(fields=['source_farrowing', 'transfer_date'], name='piglet_transfer_source_idx'),
        ),
        migrations.AddIndex(
            model_name='piglettransfermodel',
            index=models.Index(fields=['target_farrowing', 'transfer_date'], name='piglet_transfer_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='piglettransfermodel',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='piglet_transfer_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='piglettransfermodel',
            constraint=models.CheckConstraint(condition=models.Q(('source_farrowing', models.F('target_farrowing')), _negated=True), name='piglet_transfer_different_cycles'),
        ),
    ]
