# Generated by Django 6.0.5 on 2026-07-28 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sows', '0014_vaccination_plan_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationplanmodel',
            name='starts_on',
            field=models.DateField(
                blank=True,
                help_text=(
                    'Pierwszy dzień, od którego plan może generować terminy.'
                ),
                null=True,
                verbose_name='Początek obowiązywania planu',
            ),
        ),
        migrations.AlterField(
            model_name='sowmodel',
            name='entry_date',
            field=models.DateField(
                default=django.utils.timezone.localdate,
            ),
        ),
    ]
