# Generated by Django 6.0.5 on 2026-06-21 16:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0005_auditlogmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_categories', to='farms.farmmodel')),
            ],
            options={
                'verbose_name': 'Kategoria kosztu',
                'verbose_name_plural': 'Kategorie kosztów',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data kosztu')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Kwota')),
                ('description', models.TextField(verbose_name='Opis')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Numer dokumentu')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Dostawca')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Opłacony')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='costs.costcategorymodel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_costs', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='farms.farmmodel')),
            ],
            options={
                'verbose_name': 'Koszt',
                'verbose_name_plural': 'Koszty',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='costcategorymodel',
            constraint=models.UniqueConstraint(fields=('farm', 'name'), name='unique_cost_category_name_per_farm'),
        ),
        migrations.AddIndex(
            model_name='costmodel',
            index=models.Index(fields=['farm', 'date'], name='cost_farm_date_idx'),
        ),
        migrations.AddIndex(
            model_name='costmodel',
            index=models.Index(fields=['farm', 'is_paid'], name='cost_farm_paid_idx'),
        ),
    ]
