# Generated by Django 6.0.5 on 2026-06-11 16:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class CreateModelIfMissing(migrations.CreateModel):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        with schema_editor.connection.cursor() as cursor:
            existing_tables = schema_editor.connection.introspection.table_names(cursor)

        if model._meta.db_table in existing_tables:
            return

        schema_editor.create_model(model)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        return


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateModelIfMissing(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa składnika')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('is_in_bin', models.BooleanField(default=False, verbose_name='Przechowywane w binie (silosie)')),
            ],
        ),
        CreateModelIfMissing(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nazwa receptury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        CreateModelIfMissing(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data dostawy')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość (kg)')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, verbose_name='Cena za kg')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='feed.ingredientmodel', verbose_name='Składnik')),
            ],
        ),
        CreateModelIfMissing(
            name='IngredientPriceConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=5, max_digits=14, verbose_name='Domyślna cena za kg')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_config', to='feed.ingredientmodel', verbose_name='Składnik')),
            ],
        ),
        CreateModelIfMissing(
            name='RecipeItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Procentowy udział (%)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='feed.ingredientmodel', verbose_name='Składnik')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.recipemodel', verbose_name='Receptura')),
            ],
        ),
        CreateModelIfMissing(
            name='ProductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data zaplanowania/produkcji')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Godzina (Kolejność)')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość (kg)')),
                ('custom_recipe_data', models.JSONField(blank=True, help_text="Format: {'id_skladnika': procent_udzialu}", null=True, verbose_name='Jednorazowo zmienione proporcje')),
                ('status', models.CharField(choices=[('QUEUED', 'W kolejce'), ('STAGE_1_DONE', 'Etap 1 zakończony (Biny)'), ('COMPLETED', 'Zakończone')], default='QUEUED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='feed.recipemodel', verbose_name='Bazuje na recepturze')),
            ],
        ),
    ]
