# Generated by Django 6.0.5 on 2026-05-29 15:48

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa składnika')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis/Uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa receptury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Data dostawy')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość (kg)')),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cena za kg (informacyjnie)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.ingredientmodel', verbose_name='Składnik')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientPriceConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='Cena za kg do kalkulatora')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_config', to='feed.ingredientmodel')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)], verbose_name='Procent (%)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.ingredientmodel')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.recipemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Data śrutowania')),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10, verbose_name='Ilość (kg)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.recipemodel', verbose_name='Receptura')),
            ],
        ),
    ]
