# Generated by Django 6.0.5 on 2026-06-03 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientmodel',
            name='is_in_bin',
            field=models.BooleanField(default=False, verbose_name='Przechowywane w binie (silosie)'),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='custom_recipe_data',
            field=models.JSONField(blank=True, help_text="Format: {'id_skladnika': procent_udzialu}", null=True, verbose_name='Jednorazowo zmienione proporcje'),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'W kolejce'), ('STAGE_1_DONE', 'Etap 1 zakończony (Biny)'), ('COMPLETED', 'Zakończone')], default='QUEUED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='date',
            field=models.DateField(verbose_name='Data dostawy'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deliveries', to='feed.ingredientmodel', verbose_name='Składnik'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena za kg'),
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='ingredientpriceconfigmodel',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_config', to='feed.ingredientmodel', verbose_name='Składnik'),
        ),
        migrations.AlterField(
            model_name='ingredientpriceconfigmodel',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Domyślna cena za kg'),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='date',
            field=models.DateField(verbose_name='Data zaplanowania/produkcji'),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ilość (kg)'),
        ),
        migrations.AlterField(
            model_name='productionmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='feed.recipemodel', verbose_name='Bazuje na recepturze'),
        ),
        migrations.AlterField(
            model_name='recipeitemmodel',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='feed.ingredientmodel', verbose_name='Składnik'),
        ),
        migrations.AlterField(
            model_name='recipeitemmodel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Procentowy udział (%)'),
        ),
        migrations.AlterField(
            model_name='recipeitemmodel',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.recipemodel', verbose_name='Receptura'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nazwa receptury'),
        ),
    ]
