# Generated by Django 6.0.5 on 2026-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_ingredientmodel_is_in_bin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionmodel',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina (Kolejność)'),
        ),
    ]
