# Generated by Django 6.0.5 on 2026-06-25 21:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


KG_QUANT = Decimal('0.01')
MONEY_QUANT = Decimal('0.01')
PRICE_QUANT = Decimal('0.00001')


def quantize(value, quantum):
    return Decimal(value or 0).quantize(quantum, rounding=ROUND_HALF_UP)


def initialize_fifo_state(apps, schema_editor):
    Delivery = apps.get_model('feed', 'DeliveryModel')
    InventoryMovement = apps.get_model('feed', 'InventoryMovementModel')
    Production = apps.get_model('feed', 'ProductionModel')
    RecipeItem = apps.get_model('feed', 'RecipeItemModel')
    Usage = apps.get_model('feed', 'ProductionIngredientUsageModel')

    for delivery in Delivery.objects.all().iterator():
        Delivery.objects.filter(pk=delivery.pk).update(
            remaining_quantity_kg=quantize(delivery.quantity_kg, KG_QUANT),
        )

    productions = Production.objects.filter(status='COMPLETED').select_related('recipe').order_by('date', 'time', 'id')
    for production in productions.iterator():
        farm_id = production.recipe.farm_id
        requirements = []
        existing_movements = InventoryMovement.objects.filter(
            farm_id=farm_id,
            movement_type='PRODUCTION_USAGE',
            source_model='feed.ProductionModel',
            source_id=str(production.pk),
        ).select_related('ingredient').order_by('ingredient_id', 'id')

        for movement in existing_movements:
            quantity = quantize(abs(movement.quantity_kg), KG_QUANT)
            if quantity > 0:
                requirements.append({
                    'ingredient_id': movement.ingredient_id,
                    'ingredient_name': movement.ingredient.name,
                    'quantity_kg': quantity,
                })

        if not requirements:
            custom = production.custom_recipe_data or {}
            for item in RecipeItem.objects.filter(recipe_id=production.recipe_id).select_related('ingredient'):
                percentage = Decimal(str(custom.get(str(item.ingredient_id), item.percentage)))
                quantity = quantize(production.quantity_kg * percentage / Decimal('100.00'), KG_QUANT)
                if quantity > 0:
                    requirements.append({
                        'ingredient_id': item.ingredient_id,
                        'ingredient_name': item.ingredient.name,
                        'quantity_kg': quantity,
                    })

        total_cost = Decimal('0.00')
        partial = False
        missing_messages = []
        for requirement in requirements:
            required_kg = requirement['quantity_kg']
            remaining_to_allocate = required_kg
            ingredient_cost = Decimal('0.00')
            deliveries = Delivery.objects.filter(
                ingredient_id=requirement['ingredient_id'],
                date__lte=production.date,
                price_per_kg__isnull=False,
                remaining_quantity_kg__gt=0,
            ).order_by('date', 'id')

            for delivery in deliveries:
                if remaining_to_allocate <= 0:
                    break
                available = quantize(delivery.remaining_quantity_kg, KG_QUANT)
                if available <= 0:
                    continue
                quantity = min(available, remaining_to_allocate)
                quantity = quantize(quantity, KG_QUANT)
                cost = quantize(quantity * delivery.price_per_kg, MONEY_QUANT)
                Usage.objects.create(
                    farm_id=farm_id,
                    production_id=production.pk,
                    ingredient_id=requirement['ingredient_id'],
                    delivery_id=delivery.pk,
                    quantity_kg=quantity,
                    unit_price=delivery.price_per_kg,
                    cost=cost,
                )
                ingredient_cost += cost
                remaining_to_allocate = quantize(remaining_to_allocate - quantity, KG_QUANT)
                delivery.remaining_quantity_kg = quantize(delivery.remaining_quantity_kg - quantity, KG_QUANT)
                delivery.save(update_fields=['remaining_quantity_kg'])

            if remaining_to_allocate > 0:
                partial = True
                missing_messages.append(f"{requirement['ingredient_name']}: {remaining_to_allocate:.2f} kg")
                Usage.objects.create(
                    farm_id=farm_id,
                    production_id=production.pk,
                    ingredient_id=requirement['ingredient_id'],
                    delivery_id=None,
                    quantity_kg=remaining_to_allocate,
                    unit_price=Decimal('0.00000'),
                    cost=Decimal('0.00'),
                )

            unit_price = None
            if required_kg > 0 and ingredient_cost > 0:
                unit_price = quantize(ingredient_cost / required_kg, PRICE_QUANT)
            InventoryMovement.objects.update_or_create(
                farm_id=farm_id,
                ingredient_id=requirement['ingredient_id'],
                movement_type='PRODUCTION_USAGE',
                source_model='feed.ProductionModel',
                source_id=str(production.pk),
                defaults={
                    'quantity_kg': -required_kg,
                    'unit_price': unit_price,
                    'movement_date': production.date,
                    'note': 'Migracja FIFO istniejącej produkcji',
                },
            )
            total_cost += ingredient_cost

        cost_per_kg = Decimal('0.00000')
        if production.quantity_kg:
            cost_per_kg = quantize(total_cost / production.quantity_kg, PRICE_QUANT)
        note = ''
        if partial:
            note = 'Częściowy koszt - brak rozliczalnych dostaw FIFO: ' + ', '.join(missing_messages)
        Production.objects.filter(pk=production.pk).update(
            feed_cost_total=quantize(total_cost, MONEY_QUANT),
            feed_cost_per_kg=cost_per_kg,
            feed_cost_is_partial=partial,
            feed_cost_note=note[:255],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farmsettings_visible_modules'),
        ('feed', '0004_inventory_movements_and_require_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='remaining_quantity_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pozostało do rozliczenia FIFO (kg)'),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='feed_cost_is_partial',
            field=models.BooleanField(default=False, verbose_name='Koszt składników jest częściowy'),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='feed_cost_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Uwagi do kosztu składników'),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='feed_cost_per_kg',
            field=models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=14, verbose_name='Koszt składników paszy za kg'),
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='feed_cost_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Koszt składników paszy'),
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='quantity_kg',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ilość (kg)'),
        ),
        migrations.CreateModel(
            name='ProductionIngredientUsageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Zużyta ilość (kg)')),
                ('unit_price', models.DecimalField(decimal_places=5, default=Decimal('0.00000'), max_digits=14, verbose_name='Cena jednostkowa')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Koszt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_usages', to='feed.deliverymodel', verbose_name='Dostawa FIFO')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_ingredient_usages', to='farms.farmmodel', verbose_name='Gospodarstwo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='production_usages', to='feed.ingredientmodel', verbose_name='Składnik')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_usages', to='feed.productionmodel', verbose_name='Produkcja paszy')),
            ],
            options={
                'verbose_name': 'Rozliczenie składnika FIFO',
                'verbose_name_plural': 'Rozliczenia składników FIFO',
                'ordering': ('production_id', 'ingredient__name', 'delivery__date', 'delivery_id', 'id'),
                'indexes': [models.Index(fields=['farm', 'ingredient', 'production'], name='fifo_usage_farm_ing_prod_idx'), models.Index(fields=['delivery'], name='fifo_usage_delivery_idx')],
                'constraints': [models.UniqueConstraint(fields=('production', 'ingredient', 'delivery'), name='unique_fifo_usage_per_delivery'), models.CheckConstraint(condition=models.Q(('quantity_kg__gt', 0)), name='fifo_usage_quantity_positive')],
            },
        ),
        migrations.RunPython(initialize_fifo_state, migrations.RunPython.noop),
    ]
