# Generated by Django 6.0.5 on 2026-06-03 17:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_ingredientpriceconfigmodel_price_per_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpriceconfigmodel',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Domyślna cena za kg'),
        ),
        migrations.AlterField(
            model_name='recipeitemmodel',
            name='percentage',
            field=models.DecimalField(decimal_places=5, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Procentowy udział (%)'),
        ),
    ]
