# Generated by Codex on 2026-07-01

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_recipe_versions(apps, schema_editor):
    Recipe = apps.get_model('feed', 'RecipeModel')
    RecipeItem = apps.get_model('feed', 'RecipeItemModel')
    RecipeVersion = apps.get_model('feed', 'RecipeVersionModel')
    RecipeVersionItem = apps.get_model('feed', 'RecipeVersionItemModel')
    Production = apps.get_model('feed', 'ProductionModel')

    for recipe in Recipe.objects.all().iterator():
        current_version = (
            RecipeVersion.objects
            .filter(recipe_id=recipe.pk, is_current=True)
            .order_by('-version_number', '-id')
            .first()
        )
        if current_version is None:
            current_version, _ = RecipeVersion.objects.get_or_create(
                recipe_id=recipe.pk,
                version_number=1,
                defaults={
                    'valid_from': recipe.created_at or timezone.now(),
                    'is_current': True,
                    'change_note': 'Wersja startowa utworzona podczas migracji.',
                },
            )
            if not current_version.is_current:
                RecipeVersion.objects.filter(pk=current_version.pk).update(is_current=True, valid_to=None)
                current_version.is_current = True

        existing_ingredient_ids = set(
            RecipeVersionItem.objects
            .filter(recipe_version_id=current_version.pk)
            .values_list('ingredient_id', flat=True)
        )
        version_items = []
        for item in RecipeItem.objects.filter(recipe_id=recipe.pk).iterator():
            if item.ingredient_id in existing_ingredient_ids:
                continue
            version_items.append(RecipeVersionItem(
                recipe_version_id=current_version.pk,
                ingredient_id=item.ingredient_id,
                percentage=item.percentage,
            ))
        if version_items:
            RecipeVersionItem.objects.bulk_create(version_items)

        Production.objects.filter(
            recipe_id=recipe.pk,
            recipe_version__isnull=True,
        ).update(recipe_version_id=current_version.pk)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_deliverymodel_remaining_quantity_kg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVersionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numer wersji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(verbose_name='Obowiązuje od')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Obowiązuje do')),
                ('change_note', models.CharField(blank=True, max_length=255, verbose_name='Opis zmiany')),
                ('is_current', models.BooleanField(default=True, verbose_name='Aktualna wersja')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipe_versions', to=settings.AUTH_USER_MODEL, verbose_name='Utworzona przez')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='feed.recipemodel', verbose_name='Receptura')),
            ],
            options={
                'verbose_name': 'Wersja receptury',
                'verbose_name_plural': 'Wersje receptur',
                'ordering': ('recipe_id', '-version_number'),
            },
        ),
        migrations.CreateModel(
            name='RecipeVersionItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Procentowy udział (%)')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='feed.ingredientmodel', verbose_name='Składnik')),
                ('recipe_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='feed.recipeversionmodel', verbose_name='Wersja receptury')),
            ],
            options={
                'verbose_name': 'Pozycja wersji receptury',
                'verbose_name_plural': 'Pozycje wersji receptur',
                'ordering': ('ingredient__name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='productionmodel',
            name='recipe_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='feed.recipeversionmodel', verbose_name='Wersja receptury'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionmodel',
            constraint=models.UniqueConstraint(fields=('recipe', 'version_number'), name='unique_recipe_version_number'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionmodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('recipe',), name='unique_current_recipe_version'),
        ),
        migrations.AddIndex(
            model_name='recipeversionmodel',
            index=models.Index(fields=['recipe', 'is_current'], name='recipe_version_current_idx'),
        ),
        migrations.AddConstraint(
            model_name='recipeversionitemmodel',
            constraint=models.UniqueConstraint(fields=('recipe_version', 'ingredient'), name='unique_ingredient_per_recipe_version'),
        ),
        migrations.RunPython(backfill_recipe_versions, migrations.RunPython.noop),
    ]
