# Generated by Django 6.0.5 on 2026-06-17 19:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_assign_legacy_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_check_after_days', models.PositiveIntegerField(default=30)),
                ('gestation_days', models.PositiveIntegerField(default=114)),
                ('farrowing_alert_days_ahead', models.PositiveIntegerField(default=7)),
                ('vaccination_alert_days_ahead', models.PositiveIntegerField(default=7)),
                ('allow_farrowing_without_pregnancy_check', models.BooleanField(default=True)),
                ('ask_before_auto_pregnancy_check', models.BooleanField(default=True)),
                ('low_stock_threshold_kg', models.DecimalField(decimal_places=2, default=Decimal('500'), max_digits=10)),
                ('default_production_quantity_kg', models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=10)),
                ('default_dashboard_period', models.CharField(default='6m', max_length=20)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='farms.farmmodel')),
            ],
            options={
                'verbose_name': 'Ustawienia gospodarstwa',
                'verbose_name_plural': 'Ustawienia gospodarstw',
            },
        ),
    ]
