# Generated by Django 6.0.5 on 2026-06-25 22:59

import farms.module_registry
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farmsettings_visible_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsettingsmodel',
            name='nav_modules',
            field=models.JSONField(blank=True, default=farms.module_registry.default_nav_modules),
        ),
    ]
