"""
Django settings for managerGospodarstwa project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import environ
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

TESTING = 'pytest' in sys.modules or any(
    Path(arg).name.startswith('pytest') or arg == 'test'
    for arg in sys.argv
)
DEBUG = env.bool('DEBUG', default=False)
CACHE_URL = env('CACHE_URL', default='')
CACHE_KEY_PREFIX = env('CACHE_KEY_PREFIX', default='manager_gospodarstwa')


def _cache_backend_config(*, cache_url: str, testing: bool) -> dict:
    if testing:
        return {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
            'KEY_PREFIX': CACHE_KEY_PREFIX,
        }

    if cache_url.startswith(('redis://', 'rediss://')):
        return {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': cache_url,
            'KEY_PREFIX': CACHE_KEY_PREFIX,
        }

    return {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'manager-gospodarstwa-cache',
        'KEY_PREFIX': CACHE_KEY_PREFIX,
    }


CACHES = {
    'default': _cache_backend_config(cache_url=CACHE_URL, testing=TESTING),
}

if DEBUG or TESTING:
    SECRET_KEY = env('SECRET_KEY', default='django-insecure-local-dev-test-key')
else:
    SECRET_KEY = env('SECRET_KEY')

default_allowed_hosts = ['127.0.0.1', 'localhost', 'testserver'] if DEBUG or TESTING else []
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=default_allowed_hosts)
RENDER_EXTERNAL_HOSTNAME = env('RENDER_EXTERNAL_HOSTNAME', default='')
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])
if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f'https://{RENDER_EXTERNAL_HOSTNAME}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)

if not DEBUG and not TESTING:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=True)
    CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=True)
    SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=True)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'modules_home'


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'farms',
    'sows',
    'sales',
    'feed',
    'costs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'farms.middleware.CurrentFarmMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


if DEBUG or TESTING:

    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

WHITENOISE_MANIFEST_STRICT = False

ROOT_URLCONF = 'managerGospodarstwa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'farms.context_processors.current_farm',
            ],
        },
    },
]

WSGI_APPLICATION = 'managerGospodarstwa.wsgi.application'


# Database

database_variable = "TEST_DATABASE_URL" if TESTING else "DATABASE_URL"
database_url = env(database_variable, default="")

if not database_url:
    raise RuntimeError(f"Brak wymaganej zmiennej {database_variable}.")

DATABASES = {
    "default": env.db(database_variable),
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_THOUSAND_SEPARATOR = True
THOUSAND_SEPARATOR = ' '
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3

USE_TZ = True
