nname: Django Remote Migrate

on:
  push:
    branches: [ main ]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: 'temporary-key-for-migrations'
        DEBUG: 'True'
      run: |
        python manage.py migrate

    - name: Create Superuser
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: 'temporary-key-for-migrations'
        DJANGO_SUPERUSER_USERNAME: 'toniemasz'
        DJANGO_SUPERUSER_EMAIL: 'tomaszf600@gmail.com'
        DJANGO_SUPERUSER_PASSWORD: 'Skorpion2003!'
      run: |
        python manage.py createsuperuser --noinput || echo "Admin już istnieje lub wystąpił błąd"