# Generated by Django 6.0.5 on 2026-05-29 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PigSaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=datetime.date.today, verbose_name='Data sprzedaży')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ilość sprzedanych sztuk')),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Waga całkowita (kg)')),
                ('meat_class', models.CharField(choices=[('S', 'Klasa S'), ('E', 'Klasa E'), ('U', 'Klasa U'), ('R', 'Klasa R'), ('O', 'Klasa O'), ('P', 'Klasa P'), ('INNA', 'Inna klasa')], default='INNA', max_length=10, verbose_name='Klasa mięsności')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cena za kg (PLN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
