# Generated by Django 6.0.5 on 2026-06-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pigsalemodel',
            name='slaughter_date',
        ),
        migrations.RemoveField(
            model_name='pigsalemodel',
            name='supplier_name',
        ),
    ]
