# Generated by Django 6.0.5 on 2026-07-28 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_pigsalemodel_settlement_review_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigsalemodel',
            name='sale_date',
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.localdate,
                null=True,
                verbose_name='Data sprzedaży',
            ),
        ),
    ]
